### ISSUE TITLE
[Question] How to load data via Ajax for a sub component?

### ISSUE THREAD

**Issue by chinleung** [inertiajs/inertia-vue#126]
I have a listing of models similar to the PingCRM demo (http://demo.inertiajs.com/contacts). However, in my table, when we click on a row, instead of redirecting to the single client page, we show a side panel with the information of the contact.

So I'm wondering if there's a way to load the detail of the contact that has been clicked in the panel, without making an api endpoint to fetch the information? Otherwise it'd defeat the purpose of Inertia wouldn't it?

**Comment by reinink** [comment]
I don't think there is anything wrong with loading extra data via a separate XHR request to get extra data. There is no rule with Inertia that says you cannot load extra data via XHR.

**Comment by chinleung** [comment]
> I don't think there is anything wrong with loading extra data via a separate XHR request to get extra data. There is no rule with Inertia that says you cannot load extra data via XHR.

But wouldn't I have to make an api endpoint and protect it with Passport?

**Comment by reinink** [comment]
Yes, you'll have to create an endpoint to get this data, but you definitely do not have to use passport to protect it. Just make it a normal session auth endpoint, like all the other endpoints. Simply return JSON instead of an Inertia response. I do this once in a while myself in my apps.

Another option is to pass a query string. For example, `/contacts?id=123`. When an ID is passed to your index endpoint, load that contacts information and it include it with your Inertia response. In your Vue component, check if a contact prop is set, and show the panel if it is. This allows you to continue making Inertia responses.

**Comment by chinleung** [comment]
> Another option is to pass a query string. For example, `/contacts?id=123`. When an ID is passed to your index endpoint, load that contacts information and it include it with your Inertia response. In your Vue component, check if a contact prop is set, and show the panel if it is. This allows you to continue making Inertia responses

Thanks! I'm going to try this out.
