### ISSUE TITLE
Using inertia-link in external package

### ISSUE THREAD

**Issue by fourstacks** [inertiajs/inertia-vue#5]
Small tip with an obvious enough solution but it tripped me up for a little bit so thought this would be worth posting for the benefit of anyone working on something similar.  (feel free to close if you want to tidy things up @reinink )

I'm building a component library for company use and some components need to use inertia-link components within them.  If you find that you need to use inertia components in a package that you will pull into your project then the best way I've found to deal with this so far is to simply register the `<inertia-link>` component globally in your project itself

```
import { InertiaLink } from 'inertia-vue'
Vue.component('inertia-link', InertiaLink);
```

Then in your package component you can use `<inertia-link>` without having to import that component anywhere.  You also do not have to pull Inertia into your package either though I would recommend listing inertia-vue as a `peerDependency` in the package.json file of your library.

Of course the other benefit of globally registering the inertia-link component in your project is that you don't have to repeatedly import it in all your page components etc so it's probably worth doing whether you're developing an package that your app will consume or not.

**Comment by reinink** [comment]
Yep, totally. Right now inertia-vue doesn't register any components. I'm leaving this up to the developer to decide.

**Comment by reinink** [comment]
I reconsidered this, and decided to include an Inertia plugin that will automatically register `<inertia-link>`. To do this, add the following to your `app.js` file:

```js
Vue.use(Inertia)
```

This also registers `$inertia` as a property, meaning you can access it in any component, instead of having to import Inertia each time.

I've also added a new `remember` property, which allows you to register which data properties should automatically be cached to history state. I'm going to update the docs shortly on that.

You can see the implications of all these changes in the Ping app in [this commit](https://github.com/inertiajs/pingcrm/commit/6e757083e35efd7e448cb8ad0a701a6a44cde0ed).

This is all inspired by Vue router, which does many of the [same things](https://github.com/vuejs/vue-router/blob/dev/src/install.js).

**Comment by fourstacks** [comment]
FWIW - I think this is a much more elegant solution and more in keeping with the rest of the vue ecosystem (as you pointed out with the router example).  Should make onboarding vue developers more straightforward via docs etc if the vue adapter follows conventions.  Nice work!

**Comment by reinink** [comment]
Thanks John! I agree, the plugin approach (`Vue.use()`) really made this make sense for me. If you don't want to auto-registering, simply omit registering the plugin, and register manually intead (as you've had to this point).

**Comment by reinink** [comment]
I've updated the docs to reflect these changes: https://github.com/inertiajs/inertia-vue
