### ISSUE TITLE
Route key not remembered.

### ISSUE THREAD

**Issue by itherotech-greg** [inertiajs/inertia-vue#52]
@reinink when trying to scope filter on a select input, the key in the route is replaced with "remember". 

xhr.js?cff2:160 GET http://website.test/organizations/remember/edit 404 (Not Found)

`Route::get('organizations/{organization}/edit')->name('organizations.edit')->uses('OrganizationController@edit')->middleware('auth');`

`remember: 
        'form',`

`    watch: {
        form: {
            handler: _.throttle(function() {
                let query = _.pickBy(this.form)
                this.$inertia.replace(this.route('organizations.edit', Object.keys((query).length ? query : { remember: 'forget' })))
            }, 150),
            deep: true,
        },
    },`

**Comment by harrysbaraini** [comment]
IMO it's not a Inertia issue.

You're doing it:

```
this.route('organizations.edit', Object.keys((query).length ? query : { remember: 'forget' }))
```

The key is replaced with _remember_ because you're just passing an array of Object keys. First thing that JS will resolve is `(query).length ? query : { remember: 'forget' }`. After that, `Object.keys` will get all keys in that object. This new array of keys will be passed to `this.route`.

I think you want to check the length of query by using `Object.keys(query).length`:

```
const params = Object.keys(query).length ? query : { remember: 'forget' }

this.route('organizations.edit', { organization: organization, ...params })
```

That way, you pass the Route Key and append filter keys to the URL query.

**Comment by itherotech-greg** [comment]
Thank you @harrysbaraini that helped me get it sorted out, I ended up using:


```javascript
const params = Object.keys(query).length ? query : { remember: 'forget' };

const organization = this.organization.id;

this.$inertia.replace(this.route('organizations.edit', { organization, ...params }))

```
