### ISSUE TITLE
Can Inertia do Server-side-rendering or SSR for SEO?

### ISSUE THREAD

**Issue by connecteev** [inertiajs/inertia-vue#64]
Like a lot of devs, I am building a complex, dynamic site in Laravel with lots of features. I am interested in making my Laravel app quick to render (client-side), and SEO is an important consideration because I need to be indexed well on Google. So, SSR becomes a necessity.

Tools like Nuxt.js exist for this reason. Nuxt (the vue.js framework that supports SSR in "universal" mode) essentially runs in it's own process (possibly over nodejs), and communicates with Laravel (the backend) over APIs, using something like Axios. 
This architecture works well, but now you have to write APIs to talk to the backend, which can get janky, especially when you're dealing with sessions and Auth.

My question is, can Inertia do SSR? All of my research and testing shows that it can't...but I've only been working with it for a few days, and maybe missing something. I have installed it and got it working, I've also watched all the videos on inertia, including https://reinink.ca/articles/introducing-inertia-js

Is Inertia meant to be used only for SPAs? Or can it do Server-side-rendering or SSR for SEO? Most importantly, how can I do that? I can't find examples of this anywhere.

**Comment by rakk7** [comment]
I was concerned about this for a while now.. I don't think you need to do SSR for Inertia.
### Does Inertia have problems with SEO?

**A very important point:**
Since Inertia is not the same as any **Full SPA** frameworks.. meaning the routing is handled by the server, which also means that the component and component's data are rendered all together ( not the same as full SPA which you render the component then make an ajax request to get the data from server while maybe showing a spinner until data is loaded) and this is very important for SEO ( the data will always be there on the first page load ).

I will only talk about Googlebot, since other search engines does not render JS ( and also Google is the only engine I care about really! ). I published a website for testing Inertia and Google SEO, and I used google search console for testing the website. I used **URL inspection** to see if Google does render the component or not, and the result was Googlebot does render it fully. Then I asked google to index a given URL and the result was Googlebot has indexed the page as how you would expect. page ( title - description - keywords - content) are all indexed fine.


I recommend that you watch this playlist to give you an idea how does Goolebot index a **Full SPA**: https://www.youtube.com/watch?v=LXF8bM4g-J4&list=PLKoqnv2vTMUPOalM1zuWDP9OQl851WMM9

I published this website 2 days a go and there is a lot of testing to be done.. I will keep an eye on it and maybe I will write a blog about it.

**Comment by sebastiandedeyne** [comment]
Inertia doesn't support SSR, and I wouldn't count on it yet either. It's something we might look into in the future, but it's not a priority.

@rakk7 feel free to reply here if you'd write that post, sounds interesting!

**Comment by Dhofca** [comment]
> I published this website 2 days a go and there is a lot of testing to be done.. I will keep an eye on it and maybe I will write a blog about it.

I'm curious if you have any conclusions you want to share? :)

**Comment by connecteev** [comment]
@rakk7 @sebastiandedeyne missed this notification in github..sorry for the late response, thanks for the clarity. When inertia does support SSR I'll come back to this because I really need that at the moment.

**Comment by fat4lix** [comment]
I don't think SSR is an Inertia problem.  This is a problem of implementation on a particular framework. If you need SSR for indexing by search engines, you only need to implement it for the first request of the page, because search engines do not click on links as users, they just make http requests for found links and load them, such as curl. I think to implement this should not be a tricky. There are an article on how to do it in Laravel + Vue https://vuejsdevelopers.com/2017/11/06/vue-js-laravel-server-side-rendering/

I think you can extend Inertia facade so that when you call the render function, it checks the request headers, and if it's not ajax, it executes SSR entrypoint. But that's the theory.

**Comment by StefanNeuser** [comment]
> Note that as of now, Google and Bing can index synchronous JavaScript applications just fine. Synchronous being the key word there. If your app starts with a loading spinner, then fetches content via Ajax, the crawler will not wait for you to finish. This means if you have content fetched asynchronously on pages where SEO is important, SSR might be necessary.

From https://ssr.vuejs.org/#what-is-server-side-rendering-ssr

**Comment by sebastiandedeyne** [comment]
This is not true for Google anymore. Google also indexes content loaded through AJAX, however, it takes Google a _lot_ (days) longer to index this kind of content over server rendered content. For SEO-critical apps, this might be a no-go.

**Comment by StefanNeuser** [comment]
> This is not true for Google anymore. Google also indexes content loaded through AJAX, however, it takes Google a _lot_ (days) longer to index this kind of content over server rendered content. For SEO-critical apps, this might be a no-go.

Okay but as i described above it should be fine for google because no xhr is made for first page visits.

**Comment by connecteev** [comment]
> This is not true for Google anymore. Google also indexes content loaded through AJAX, however, it takes Google a _lot_ (days) longer to index this kind of content over server rendered content. For SEO-critical apps, this might be a no-go.

Would love to see Inertia support SSR for SEO! It will eliminate the need to use Nuxt over APIs

**Comment by 7ammer** [comment]
This link describes how to get SSR to work with Laravel + Vue:
https://dev.to/michi/the-troubles-implementing-ssr-into-a-laravel-vue-app-3m5f

Thought it might be useful.

**Comment by joevallender** [comment]
I've written a quick blog about setting up pre-rendering for Laravel, Inertia, and Vue using Rendertron installed on a standard Forge server.
https://medium.com/@joevallender/pre-rendering-inertia-js-for-seo-using-laravel-rendertron-nginx-55634ad1796a
