### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by IamMHC** [inertiajs/inertia-vue#73]
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve '@inertiajs/inertia-vue'

**Comment by Juhlinus** [comment]
Hello @IamMHC !

Make sure that you've installed the new dependencies, since the name of them changed recently.

Your packages.json file should contain the following lines:

```json
    "devDependencies": {
        "@inertiajs/inertia": "^0.1.0",
        "@inertiajs/inertia-vue": "^0.1.0",
    }
```

Your `resources/js/app.js` file should look something like this:
```javascript
import { InertiaApp } from '@inertiajs/inertia-vue'
import Vue from 'vue'

Vue.use(InertiaApp)

let app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => import(`@/Pages/${name}`).then(module => module.default),
    },
  }),
}).$mount(app)
```
Make sure you have the latest versions of all the packages as well.

Write back if you still have any issues. 😃

**Comment by IamMHC** [comment]
Again same issue
This dependency was not found:

* @inertiajs/inertia-vue in ./resources/js/app.js

To install it, you can run: npm install --save @inertiajs/inertia-vue

**Comment by IamMHC** [comment]
but i have in node_module

**Comment by IamMHC** [comment]
Before package.json  
 "@inertiajs/inertia-vue": "github:inertiajs/inertia-vue",
update with 
"@inertiajs/inertia-vue": "^0.1.0",
issue solved 
Thank you very much

**Comment by reinink** [comment]
Glad you got it figured out. Be sure to review the 0.1 upgrade guide, [here](https://github.com/inertiajs/inertia/releases/tag/v0.1.0).
