### ISSUE TITLE
Page visit without reloading Layout?

### ISSUE THREAD

**Issue by divdax** [inertiajs/inertia-vue#84]
It is possible only to render another component/content of a link instead of the whole page?
In my Layout.vue i've a timer in the app navbar and it gets resetted when i visit another page.

Any ideas?

**Comment by RSpeekenbrink** [comment]
It doesn't seem like that's possible since there is nothing like <router-view> that specifies the part that inertia should render to without touching the surroundings. And inertia seems to insert server-side rendered templates into the app overwriting your current components.

But it is solvable, to preserve the state of the components that are also included in the fetched template. You can achieve that by passing the `preserveState` bool:

```
this.$inertia.visit('/', {method: 'get', preserveState: true});
```

Or in inertia-link components:

```
<inertia-link preserve-state href="/">Link</inertia-link>
```

**Comment by RSpeekenbrink** [comment]
partial loading is also being worked on:

https://github.com/inertiajs/inertia/pull/61

#77

**Comment by divdax** [comment]
But this means i've to add the preserve-state to every link.
Especially when i have a notification/chat component in my main Layout this wouldn't solve my problem?

**Comment by reinink** [comment]
Hey there @divdax! So, currently Inertia completely reloads the entire page, and the page is the top-level component. We're exploring ways of doing support more complex component tree structures, but there is no official support for it right now.

That said, @rodrigopedra came up with a very creative solution to doing this right now. See his comment here: https://github.com/inertiajs/inertia-vue/issues/70#issuecomment-522436578

Hope that helps! 👍

**Comment by divdax** [comment]
That's what i need. Thanks a lot @reinink!
And even more elegant see this PR #83 - pleeeease merge it! 😄
